In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import statsmodels.stats.multicomp as multi
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [8]:
aus_crime_stats

,This tab outlines the contents of the datacube and includes links to relevant webpages on the ABS website. It ranges from cell A1 to B25.,Unnamed: 1
0,Australian Bureau of Statistics,NaN
1,"Recorded Crime – Offenders, 2023–24",NaN
2,Released at 11.30am (Canberra time) Thursday 6...,NaN
3,Contents,NaN
4,Tab,Description
5,Table 6,"Offenders, Principal offence (divisions and se..."
6,Table 7,"Offenders, Principal offence by sex, New South..."
7,Table 8,"Offenders, Principal offence by sex, Victoria,..."
8,Table 9,"Offenders, Principal offence by sex, Queenslan..."
9,Table 10,"Offenders, Principal offence by sex, South Aus..."
10,Table 11,"Offenders, Principal offence by sex, Western A..."
11,Table 12,"Offenders, Principal offence by sex, Tasmania,..."
12,Table 13,"Offenders, Principal offence by sex, Northern ..."
13,Table 14,"Offenders, Principal offence by sex, Australia..."
14,Table 15,"Offenders, Sex by age, States and territories,..."
15,Table 16,"Offenders, Sex by number of times proceeded ag..."
16,Table 17,"Offenders, Age by number of times proceeded ag..."
17,Further information,NaN
18,This data comes from Recorded Crime – Offender...,NaN
19,Visit methodology to understand more about how...,NaN
20,Australian Bureau of Statistics website,NaN
21,Contact us if you have an enquiry about these ...,NaN
22,The ABS privacy policy outlines how we handle ...,NaN
23,© Commonwealth of Australia,NaN

In [9]:
new = pd.read_excel("/Users/waqarmohiuddin/Library/Mobile Documents/com~apple~Numbers/Documents/crime_stats.xlsx.numbers")

OptionError: No such keys(s): 'io.excel.zip.reader'

In [10]:
xls = pd.ExcelFile("/Users/waqarmohiuddin/Downloads/Recorded Crime - Offenders, 2023-24/3. Youth offenders.xlsx")
xls.sheet_names

['Contents',
 'Table 18',
 'Table 19',
 'Table 20',
 'Table 21',
 'Table 22',
 'Table 23',
 'Table 24',
 'Table 25']

In [11]:
youth_offenders = pd.read_excel("/Users/waqarmohiuddin/Downloads/Recorded Crime - Offenders, 2023-24/3. Youth offenders.xlsx", sheet_name="Table 21")

In [15]:
youth_offenders = pd.read_excel(
    "/Users/waqarmohiuddin/Downloads/Recorded Crime - Offenders, 2023-24/3. Youth offenders.xlsx",
    sheet_name= "Table 21",
    skiprows=4,     # skip metadata rows
    nrows=157       # table is A1–K161 → about 157 data rows
)

youth_offenders.head()

,Unnamed: 0,Number,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Offender rate(a),Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382,Unnamed: 16383
0,Principal offence(b)(c),10–11 years,12–13 years,14–17 years,Youth offenders,All offenders(d),10–11 years,12–13 years,14–17 years,Youth offenders,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,New South Wales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01 Homicide and related offences,0,0,19,18,267,0,0,4.6,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02 Acts intended to cause injury(e),58,675,3368,4100,38453,28.1,325.5,824.2,498.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,03 Sexual assault and related offences,0,36,226,259,2872,0,17.4,55.3,31.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN